FROM python:3.11-slim

WORKDIR /app

COPY "backend/requirements.txt" .
COPY "backend/requirements-local.txt" .
RUN pip install --no-cache-dir -r requirements-local.txt

COPY "backend/" /app/

EXPOSE 8082

CMD ["python", "local_server.py"]
